### ISSUE TITLE
-lMagickWand-6.Q8 not found

### ISSUE THREAD

**Issue by chika-kasymov** [naithar/MagickWand#14]
Hello!

Thanks for this library! I found your tool very helpful.

Now I have some strange error:
```
Linking ./.build/debug/App
ld: library not found for -lMagickWand-6.Q8 for architecture x86_64
<unknown>:0: error: link command failed with exit code 1 (use -v to see invocation)
<unknown>:0: error: build had 1 command failures
```

A few days ago my project built normally. I followed README but the error occurs.

**Comment by naithar** [comment]
Hello!

Recently the library switched from using .Q8 to .Q16 on MacOS as there was some issues with dependencies found by other library user. I'll be fixing this issue as soon as possible and probably switch back to use of .Q8 libraries.

There are few ways you can actually fix this:
- Manually change the `module.modulemap` file in `/Sources/CMagickWand/include` folder.
- Force module to load exactly `0.3.2` version.
- Use brew-installed imagemagick package.
- If `ls /usr/local/lib` does list `MagickWand-6.Q16` instead of `MagickWand-6.Q8`, try updating the MagickWand package itself by `rm -rf Packages/MagickWand*` and running a build script again.

**Comment by naithar** [comment]
@chika-kasymov any updates?

**Comment by chika-kasymov** [comment]
@naithar sorry, I don't have time now to check your provided solutions. I will try it in this week and write a response.

**Comment by chika-kasymov** [comment]
@naithar I tried the first solution and changed `module.modulemap` and it worked. Thanks for the help!
**PS:** It worked from the second attempt, I needed to clear my previous build which saved the previous version of `module.modulemap`.
